Basic Python

1. Sprit this String

In [ ]:
txt= "Hi there Sami"
s= txt.split()
print(s)

2. Use .format() to print the following string.
planet = "Earth"
diameter = 12742

In [ ]:
planet="earth"
diameter=12742
print('The diameter of {} is {} kilometers.'.format(planet,diameter));

The diameter of earth is 12742 kilometers.


In [ ]:
lst=[1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
a=lst[3][1][2];
print(a)

['hello']


 3. In this nest dictionary grab the word "hello"
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# NUMPY

import numpy as np
 4.1 Create an array of 10 zeros?

In [ ]:

import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


5. Create an array of all the even integers from 20 to 35

In [ ]:
import numpy as np
array=np.arange(20,34,2)
print("array of all the even integer from 20 to 35 ")
print(array)

array of all the even integer from 20 to 35 
[20 22 24 26 28 30 32]


6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
x= np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


 7. Concatenate a and b
 a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
arr=np.stack((a,b),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


Pandas
  8. Create a dataframe with 3 rows and 2 columns
import pandas as pd

In [ ]:
import pandas as pd 
data={'name':['a','b','c'],'Age':[20,21,19]}
df=pd.DataFrame(data)
print(df)

  name  Age
0    a   20
1    b   21
2    c   19


9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
from datetime import timedelta, date

def daterange(date1, date2):
    for n in range(int ((date2 - date1).days)+1):
        yield date1 + timedelta(n)

start_dt = date(2022,1,1)
end_dt = date(2022, 2, 10)
for dt in daterange(start_dt, end_dt):
    print(dt.strftime("%Y-%m-%d"))

2022-01-01
2022-01-02
2022-01-03
2022-01-04
2022-01-05
2022-01-06
2022-01-07
2022-01-08
2022-01-09
2022-01-10
2022-01-11
2022-01-12
2022-01-13
2022-01-14
2022-01-15
2022-01-16
2022-01-17
2022-01-18
2022-01-19
2022-01-20
2022-01-21
2022-01-22
2022-01-23
2022-01-24
2022-01-25
2022-01-26
2022-01-27
2022-01-28
2022-01-29
2022-01-30
2022-01-31
2022-02-01
2022-02-02
2022-02-03
2022-02-04
2022-02-05
2022-02-06
2022-02-07
2022-02-08
2022-02-09
2022-02-10


 10. Create 2D list to DataFrame
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
lists = [[1, 'aaa', 22],
[2, 'bbb', 25],
[3, 'ccc', 24]]

In [ ]:
import pandas as pd
list=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
df = pd.DataFrame(list,columns=['a','b','c'])
print(df)


   a    b   c
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
